print("Hello world")
print("What is your name ??")
myname =input()
print(myname)
print("the length of you name is:")
print(len(myname))
print("What is your age??")
age=input()
print("your age will be "+ str(int(age)+1) + " in a year")
# spam=int(spam) (U to U)
# print(spam)
print(int("99"))
num=99
print(num)
print(str(num))
print(int(7.7))
print(int(7.7)+1)
bacon=20
print(int(bacon + 2))
ar=99
print("I have eaten " + str(ar) +  " burritos")
spam= True
print(spam)
print(42==42)
print(2==3)
print(4!=6 and 2==2)
 # print(("dog"!="cat") and ("man" != "woman" )) (U to U)
print(not True)
print(not not not not True)
print((4<5) and (5<6)) #bool +_comp op
print((2 + 2 == 4) and not (2 + 2 == 5) and (2 * 2 == 2 + 2))